server:
    port: 8090

spring:
    application:
        name: microservicio-gateway
    cloud:
        gateway:
            routes:
            -   id: microservicio-usuarios
                uri: lb://microservicio-usuarios
                predicates: Path=/api/alumnos/**
                filters: StripPrefix=2

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

